"""items track inventory and available qty

Revision ID: 06ae79adbd2c
Revises: c861b9d602ab
Create Date: 2026-08-05 15:02:27.993228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ae79adbd2c'
down_revision: Union[str, None] = 'c861b9d602ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows to False in the same statement — dropped
    # right after so the app-level default (app/models/item.py) stays the sole source
    # of truth for new inserts, matching every other boolean column in this schema.
    op.add_column(
        'items', sa.Column('track_inventory', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('items', 'track_inventory', server_default=None)
    op.add_column('items', sa.Column('available_qty', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'available_qty')
    op.drop_column('items', 'track_inventory')
    # ### end Alembic commands ###
