"""waiter login linking

Revision ID: 1d9a272d7771
Revises: 06ae79adbd2c
Create Date: 2026-08-05 15:57:56.684135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9a272d7771'
down_revision: Union[str, None] = '06ae79adbd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiters', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f('uq_waiters_user_id'), 'waiters', ['user_id'])
    op.create_foreign_key(op.f('fk_waiters_user_id_users'), 'waiters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_waiters_user_id_users'), 'waiters', type_='foreignkey')
    op.drop_constraint(op.f('uq_waiters_user_id'), 'waiters', type_='unique')
    op.drop_column('waiters', 'user_id')
    # ### end Alembic commands ###
