"""initial schema

Revision ID: 5cadf97c7c21
Revises: 
Create Date: 2026-08-02 14:25:00.930067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cadf97c7c21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_locations', sa.Integer(), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code IN ('lite', 'pro', 'pro_max')", name=op.f('ck_plans_ck_plans_code_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('tenants',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('door_no', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pincode ~ '^[1-9][0-9]{5}$'", name=op.f('ck_tenants_ck_tenants_pincode_format')),
    sa.CheckConstraint("state IN ('Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry')", name=op.f('ck_tenants_ck_tenants_state_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('categories',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ta', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_categories_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('ix_categories_tenant_id_id', 'categories', ['tenant_id', 'id'], unique=False)
    op.create_table('discount_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coupon_code', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('flat_percent', 'item_level', 'coupon')", name=op.f('ck_discount_rules_ck_discount_rules_type_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_discount_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_rules'))
    )
    op.create_index('ix_discount_rules_tenant_id_id', 'discount_rules', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_discount_rules_tenant_id_coupon_code', 'discount_rules', ['tenant_id', 'coupon_code'], unique=True, postgresql_where=sa.text('coupon_code IS NOT NULL'))
    op.create_table('seating_sections',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ta', sa.String(length=100), nullable=True),
    sa.Column('is_seating', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_seating_sections_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seating_sections'))
    )
    op.create_index('ix_seating_sections_tenant_id_id', 'seating_sections', ['tenant_id', 'id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_cycle IN ('monthly', 'yearly')", name=op.f('ck_subscriptions_ck_subscriptions_billing_cycle_valid')),
    sa.CheckConstraint("payment_status IN ('paid', 'pending', 'overdue')", name=op.f('ck_subscriptions_ck_subscriptions_payment_status_valid')),
    sa.CheckConstraint("status IN ('active', 'suspended', 'cancelled')", name=op.f('ck_subscriptions_ck_subscriptions_status_valid')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_subscriptions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index('ix_subscriptions_tenant_id_id', 'subscriptions', ['tenant_id', 'id'], unique=False)
    op.create_table('tax_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tax_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_rules'))
    )
    op.create_index('ix_tax_rules_tenant_id_id', 'tax_rules', ['tenant_id', 'id'], unique=False)
    op.create_table('tenant_locations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('door_no', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pincode ~ '^[1-9][0-9]{5}$'", name=op.f('ck_tenant_locations_ck_tenant_locations_pincode_format')),
    sa.CheckConstraint("state IN ('Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry')", name=op.f('ck_tenant_locations_ck_tenant_locations_state_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_locations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_locations'))
    )
    op.create_index('ix_tenant_locations_tenant_id_id', 'tenant_locations', ['tenant_id', 'id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('incentive_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_tenant_id_id', 'users', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_users_tenant_id_user_id', 'users', ['tenant_id', 'user_id'], unique=True, postgresql_where=sa.text('tenant_id IS NOT NULL'))
    op.create_index('uq_users_user_id_platform', 'users', ['user_id'], unique=True, postgresql_where=sa.text('tenant_id IS NULL'))
    op.create_table('audit_log',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_log_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_tenant_id_id', 'audit_log', ['tenant_id', 'id'], unique=False)
    op.create_table('hotel_master',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('door_no', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('show_tamil_names', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gstin IS NULL OR gstin ~ '^[0-9]{2}[A-Z0-9]{13}$'", name=op.f('ck_hotel_master_ck_hotel_master_gstin_format')),
    sa.CheckConstraint("pincode ~ '^[1-9][0-9]{5}$'", name=op.f('ck_hotel_master_ck_hotel_master_pincode_format')),
    sa.CheckConstraint("state IN ('Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry')", name=op.f('ck_hotel_master_ck_hotel_master_state_valid')),
    sa.ForeignKeyConstraint(['location_id'], ['tenant_locations.id'], name=op.f('fk_hotel_master_location_id_tenant_locations')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_hotel_master_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_master')),
    sa.UniqueConstraint('location_id', name=op.f('uq_hotel_master_location_id'))
    )
    op.create_index('ix_hotel_master_tenant_id_id', 'hotel_master', ['tenant_id', 'id'], unique=False)
    op.create_table('items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ta', sa.String(length=150), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_class_id', sa.UUID(), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('is_top_seller', sa.Boolean(), nullable=False),
    sa.Column('is_combo_tile', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_items_category_id_categories')),
    sa.ForeignKeyConstraint(['tax_class_id'], ['tax_rules.id'], name=op.f('fk_items_tax_class_id_tax_rules')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index('ix_items_tenant_id_id', 'items', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_items_tenant_id_item_code', 'items', ['tenant_id', 'item_code'], unique=True, postgresql_where=sa.text('item_code IS NOT NULL'))
    op.create_table('printers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=10), nullable=False),
    sa.Column('printer_type', sa.String(length=20), nullable=False),
    sa.Column('connection_type', sa.String(length=20), nullable=False),
    sa.Column('connection_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("connection_type IN ('network', 'usb', 'local_agent')", name=op.f('ck_printers_ck_printers_connection_type_valid')),
    sa.CheckConstraint("printer_type IN ('thermal', 'dotmatrix')", name=op.f('ck_printers_ck_printers_printer_type_valid')),
    sa.CheckConstraint("target IN ('kot', 'bill')", name=op.f('ck_printers_ck_printers_target_valid')),
    sa.ForeignKeyConstraint(['location_id'], ['tenant_locations.id'], name=op.f('fk_printers_location_id_tenant_locations')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_printers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_printers'))
    )
    op.create_index('ix_printers_tenant_id_id', 'printers', ['tenant_id', 'id'], unique=False)
    op.create_table('tables',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.String(length=20), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('free', 'occupied', 'billed')", name=op.f('ck_tables_ck_tables_status_valid')),
    sa.ForeignKeyConstraint(['location_id'], ['tenant_locations.id'], name=op.f('fk_tables_location_id_tenant_locations')),
    sa.ForeignKeyConstraint(['section_id'], ['seating_sections.id'], name=op.f('fk_tables_section_id_seating_sections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tables_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables'))
    )
    op.create_index('ix_tables_tenant_id_id', 'tables', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_tables_tenant_id_location_id_table_number', 'tables', ['tenant_id', 'location_id', 'table_number'], unique=True)
    op.create_table('user_location_access',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['tenant_locations.id'], name=op.f('fk_user_location_access_location_id_tenant_locations')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_location_access_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_location_access_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_location_access'))
    )
    op.create_index('ix_user_location_access_tenant_id_id', 'user_location_access', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_user_location_access_user_id_location_id', 'user_location_access', ['user_id', 'location_id'], unique=True)
    op.create_table('waiters',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('waiter_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('incentive_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['tenant_locations.id'], name=op.f('fk_waiters_location_id_tenant_locations')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_waiters_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waiters'))
    )
    op.create_index('ix_waiters_tenant_id_id', 'waiters', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_waiters_tenant_id_location_id_waiter_number', 'waiters', ['tenant_id', 'location_id', 'waiter_number'], unique=True)
    op.create_table('item_section_prices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_section_prices_item_id_items')),
    sa.ForeignKeyConstraint(['section_id'], ['seating_sections.id'], name=op.f('fk_item_section_prices_section_id_seating_sections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_item_section_prices_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_section_prices'))
    )
    op.create_index('ix_item_section_prices_tenant_id_id', 'item_section_prices', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_item_section_prices_item_id_section_id', 'item_section_prices', ['item_id', 'section_id'], unique=True)
    op.create_table('orders',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('waiter_id', sa.UUID(), nullable=True),
    sa.Column('pos_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hold_label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'held', 'billed')", name=op.f('ck_orders_ck_orders_status_valid')),
    sa.ForeignKeyConstraint(['location_id'], ['tenant_locations.id'], name=op.f('fk_orders_location_id_tenant_locations')),
    sa.ForeignKeyConstraint(['pos_user_id'], ['users.id'], name=op.f('fk_orders_pos_user_id_users')),
    sa.ForeignKeyConstraint(['section_id'], ['seating_sections.id'], name=op.f('fk_orders_section_id_seating_sections')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_orders_table_id_tables')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_orders_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waiter_id'], ['waiters.id'], name=op.f('fk_orders_waiter_id_waiters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_tenant_id_id', 'orders', ['tenant_id', 'id'], unique=False)
    op.create_index('ix_orders_tenant_id_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_table('bills',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=30), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('waiter_id', sa.UUID(), nullable=True),
    sa.Column('pos_user_id', sa.UUID(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('round_off_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('waiter_incentive_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cashier_incentive_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['tenant_locations.id'], name=op.f('fk_bills_location_id_tenant_locations')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_bills_order_id_orders')),
    sa.ForeignKeyConstraint(['pos_user_id'], ['users.id'], name=op.f('fk_bills_pos_user_id_users')),
    sa.ForeignKeyConstraint(['section_id'], ['seating_sections.id'], name=op.f('fk_bills_section_id_seating_sections')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_bills_table_id_tables')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bills_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waiter_id'], ['waiters.id'], name=op.f('fk_bills_waiter_id_waiters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills')),
    sa.UniqueConstraint('order_id', name=op.f('uq_bills_order_id'))
    )
    op.create_index('ix_bills_tenant_id_id', 'bills', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_bills_tenant_id_bill_number', 'bills', ['tenant_id', 'bill_number'], unique=True)
    op.create_table('kot_tickets',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'preparing', 'ready')", name=op.f('ck_kot_tickets_ck_kot_tickets_status_valid')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_kot_tickets_order_id_orders')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_kot_tickets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kot_tickets'))
    )
    op.create_index('ix_kot_tickets_tenant_id_id', 'kot_tickets', ['tenant_id', 'id'], unique=False)
    op.create_index('uq_kot_tickets_tenant_id_ticket_number', 'kot_tickets', ['tenant_id', 'ticket_number'], unique=True)
    op.create_table('order_items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_kot_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_ck_order_items_quantity_positive')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_order_items_item_id_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_order_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_tenant_id_id', 'order_items', ['tenant_id', 'id'], unique=False)
    op.create_table('bill_items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_en_snapshot', sa.String(length=150), nullable=False),
    sa.Column('name_ta_snapshot', sa.String(length=150), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_items_bill_id_bills')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_bill_items_item_id_items')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bill_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_items'))
    )
    op.create_index('ix_bill_items_tenant_id_id', 'bill_items', ['tenant_id', 'id'], unique=False)
    op.create_table('kot_ticket_items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kot_ticket_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kot_ticket_id'], ['kot_tickets.id'], name=op.f('fk_kot_ticket_items_kot_ticket_id_kot_tickets')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_kot_ticket_items_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_kot_ticket_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kot_ticket_items'))
    )
    op.create_index('ix_kot_ticket_items_tenant_id_id', 'kot_ticket_items', ['tenant_id', 'id'], unique=False)
    op.create_table('payments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('upi', 'cash', 'card')", name=op.f('ck_payments_ck_payments_method_valid')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_payments_bill_id_bills')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_tenant_id_id', 'payments', ['tenant_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_tenant_id_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_kot_ticket_items_tenant_id_id', table_name='kot_ticket_items')
    op.drop_table('kot_ticket_items')
    op.drop_index('ix_bill_items_tenant_id_id', table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index('ix_order_items_tenant_id_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('uq_kot_tickets_tenant_id_ticket_number', table_name='kot_tickets')
    op.drop_index('ix_kot_tickets_tenant_id_id', table_name='kot_tickets')
    op.drop_table('kot_tickets')
    op.drop_index('uq_bills_tenant_id_bill_number', table_name='bills')
    op.drop_index('ix_bills_tenant_id_id', table_name='bills')
    op.drop_table('bills')
    op.drop_index('ix_orders_tenant_id_status', table_name='orders')
    op.drop_index('ix_orders_tenant_id_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('uq_item_section_prices_item_id_section_id', table_name='item_section_prices')
    op.drop_index('ix_item_section_prices_tenant_id_id', table_name='item_section_prices')
    op.drop_table('item_section_prices')
    op.drop_index('uq_waiters_tenant_id_location_id_waiter_number', table_name='waiters')
    op.drop_index('ix_waiters_tenant_id_id', table_name='waiters')
    op.drop_table('waiters')
    op.drop_index('uq_user_location_access_user_id_location_id', table_name='user_location_access')
    op.drop_index('ix_user_location_access_tenant_id_id', table_name='user_location_access')
    op.drop_table('user_location_access')
    op.drop_index('uq_tables_tenant_id_location_id_table_number', table_name='tables')
    op.drop_index('ix_tables_tenant_id_id', table_name='tables')
    op.drop_table('tables')
    op.drop_index('ix_printers_tenant_id_id', table_name='printers')
    op.drop_table('printers')
    op.drop_index('uq_items_tenant_id_item_code', table_name='items', postgresql_where=sa.text('item_code IS NOT NULL'))
    op.drop_index('ix_items_tenant_id_id', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_hotel_master_tenant_id_id', table_name='hotel_master')
    op.drop_table('hotel_master')
    op.drop_index('ix_audit_log_tenant_id_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_users_user_id_platform', table_name='users', postgresql_where=sa.text('tenant_id IS NULL'))
    op.drop_index('uq_users_tenant_id_user_id', table_name='users', postgresql_where=sa.text('tenant_id IS NOT NULL'))
    op.drop_index('ix_users_tenant_id_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tenant_locations_tenant_id_id', table_name='tenant_locations')
    op.drop_table('tenant_locations')
    op.drop_index('ix_tax_rules_tenant_id_id', table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_index('ix_subscriptions_tenant_id_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_seating_sections_tenant_id_id', table_name='seating_sections')
    op.drop_table('seating_sections')
    op.drop_index('uq_discount_rules_tenant_id_coupon_code', table_name='discount_rules', postgresql_where=sa.text('coupon_code IS NOT NULL'))
    op.drop_index('ix_discount_rules_tenant_id_id', table_name='discount_rules')
    op.drop_table('discount_rules')
    op.drop_index('ix_categories_tenant_id_id', table_name='categories')
    op.drop_table('categories')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('plans')
    # ### end Alembic commands ###
