"""bills status check constraint

Revision ID: c2cd2c36eb0d
Revises: 95a490b62fde
Create Date: 2026-08-06 11:24:12.759357

`bills.status` was created in the Phase 01 initial schema with no CHECK constraint,
unlike every other status-like column in this schema (orders, tables, kot_tickets,
subscriptions, ...). Alembic's autogenerate doesn't detect CHECK constraints, so this
migration is hand-written rather than autogenerated (Phase 09, CLAUDE.md §8).
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c2cd2c36eb0d'
down_revision: Union[str, None] = '95a490b62fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_check_constraint(
        "ck_bills_status_valid", "bills", "status IN ('finalized', 'void')"
    )


def downgrade() -> None:
    op.drop_constraint("ck_bills_status_valid", "bills", type_="check")
