"""platform settings singleton

Revision ID: c861b9d602ab
Revises: 3d908345eda4
Create Date: 2026-08-02 19:30:31.679961

Phase 03: maintenance-mode toggle + announcement banner. `id` is pinned to 1 by a CHECK
constraint (app/models/platform_settings.py) so there's always exactly one row — seeded
here so the app never has to special-case a missing row.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c861b9d602ab'
down_revision: Union[str, None] = '3d908345eda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('announcement_is_active', sa.Boolean(), nullable=False),
    sa.Column('announcement_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_platform_settings_ck_platform_settings_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_settings'))
    )
    op.execute(
        "INSERT INTO platform_settings (id, maintenance_mode, announcement_is_active) "
        "VALUES (1, false, false)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
