"""platform settings and subscription upgrade request

Revision ID: 42e9a7d2be2a
Revises: 69d1dba73c3c
Create Date: 2026-07-24 07:44:19.457198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e9a7d2be2a'
down_revision: Union[str, None] = '69d1dba73c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('requested_plan_id', sa.UUID(), nullable=True))
    op.add_column('subscriptions', sa.Column('upgrade_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'subscriptions_requested_plan_id_fkey',
        'subscriptions', 'plans', ['requested_plan_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_requested_plan_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'upgrade_requested_at')
    op.drop_column('subscriptions', 'requested_plan_id')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
