"""add notification reference_id

Revision ID: 6cbcfd247bdd
Revises: 42e9a7d2be2a
Create Date: 2026-07-24 08:59:23.630386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbcfd247bdd'
down_revision: Union[str, None] = '42e9a7d2be2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reference_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'reference_id')
    # ### end Alembic commands ###
